version: '3'
services:
    postgres:
      image: postgres
      ports:
        - "5433:5432"
      volumes:
        - dbdata:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=avalon
        - POSTGRES_PASSWORD=sdfklosdfs9!
        - POSTGRES_DB=avalon

    postgraphile:
      build: 
        context: .
        dockerfile: Dockerfile.server
      ports:
        - "5000:5000"

    # jsonserver:
    #   build:
    #     context: .
    #     dockerfile: Dockerfile.jsonserver
    #   volumes:
    #     - ./server/:/usr/src/app/server
    #   ports:
    #     - "4001:4001" # JSON server
    # graphql:
    #   build:
    #     context: .
    #     dockerfile: Dockerfile.graphql
    #   volumes:
    #     - ./server/:/usr/src/app/server
    #   ports:
    #     - "4000:4000" # Dev server
    web:
      build:
        context: .
        dockerfile: Dockerfile.web
      volumes: 
        - ./src/:/usr/src/app/client
        - ./public:/usr/src/app/public
      ports:
        - "3000:3000"

volumes:
  dbdata: